### PR TITLE
merge to master 'flow impls and flow api tests'

### PR DESCRIPTION
**Pull request by magnus-**

### CODE REVIEW

**Comment by ysmood** [comment]
I may do some clean work for the code. You code just don't pass the eslint.

**Comment by magnus-** [comment]
great, thanks
I forgot to run the eslint. sorry about that

**Comment by ysmood** [comment]
The format is done 6448f8e

**Comment by magnus-** [comment]
great works!

**Comment by ysmood** [comment]
Later I will add the project to Travis CI

**Comment by magnus-** [comment]
OK
I'll create a new branch for importing more unit tests from existed nokit code base

**Pull request merged**
